version: '3.8'  # Or a suitable version for your setup

services:
  data-chat-assistant:
    image: data-chat-assistant  # Replace with your image name
    build: .  # Assuming your Dockerfile is in the same directory
    ports:
      - "8080:8080"
    volumes:
      - model-data:app/llm_models  # Mapping container data to a local directory

volumes:
  model-data: # Named volume to persist VLLM models
